pipeline {
    agent any
    environment {
       DH = credentials('8a11e4cc-ae06-4d98-98c0-fe995b401e84')
    }
    stages {
        stage('Build') {
            steps {
		sh '''
			cd vote 
			docker build -t avinashg/voting-app .
		'''
	    }                    
	}
        stage('Deploy') {
            steps {
		sh '''
			docker login -u ${DH_USR} -p ${DH_PSW}
			docker push avinashg/voting-app
		'''
	    }                    
	}
    }
}
