pipeline {
    agent {
      label 'linux'
    }
    environment {
       DH = credentials('docker-hub-login')
    }
    stages {
        stage('Build') {
            steps {
		sh '''
			cd vote 
			docker build -t avinashg/voting-app .
		'''
	    }                    
	}
        stage('Deploy') {
            steps {
		sh '''
			docker login -u ${DH_USR} -p ${DH_PSW}
			docker push avinashg/voting-app
		'''
	    }                    
	}
    }
}
